# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js image as the base image
FROM node:22-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package files and source code
COPY . .

# Install dependencies
RUN --mount=type=cache,target=/root/.npm npm install

# Build the application
RUN npm run build

# Use a smaller Node.js image for the runtime
FROM node:22-alpine AS runtime

# Set the working directory
WORKDIR /app

# Copy built files from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/bin /app/bin
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json

# Expose any required ports (if needed by the application)
# EXPOSE 3000

# Start the server

ENTRYPOINT ["node", "bin/mcp-server.js"]

