export const REVISED_COMMON_WORDS_TO_REMOVE = [
  "controller",
  "api",
  "operation",
  "handler",
  "endpoint",
  "action",
  "perform",
  "execute",
  "retrieve",
  "specify", // generic verbs
  "for",
  "and",
  "the",
  "with",
  "from",
  "into",
  "onto",
  "out", // prepositions/articles
]

export const WORD_ABBREVIATIONS: Record<string, string> = {
  service: "Svc",
  services: "Svcs",
  user: "Usr",
  users: "Usrs",
  management: "Mgmt",
  manager: "Mgr",
  manage: "Mng",
  authority: "Auth",
  authorities: "Auths",
  group: "Grp",
  groups: "Grps",
  update: "Upd",
  updating: "Upd",
  updated: "Upd",
  delete: "Del",
  deleting: "Del",
  deleted: "Del",
  create: "Crt",
  creating: "Crt",
  created: "Crt",
  get: "Get",
  getting: "Get",
  list: "Lst",
  listing: "Lst",
  post: "Pst",
  put: "Put",
  patch: "Ptch",
  request: "Req",
  response: "Resp",
  parameter: "Param",
  parameters: "Params",
  config: "Cfg",
  configuration: "Config",
  configure: "Cfg",
  resource: "Res",
  resources: "Resrcs",
  identity: "Id",
  identifier: "Id",
  identification: "Id",
  identifiers: "Ids",
  application: "App",
  account: "Acct",
  information: "Info",
  notification: "Notif",
  description: "Desc",
  summary: "Summ",
  version: "Ver",
  value: "Val",
  values: "Vals",
  authentication: "Authn",
  authorization: "Authz",
  specification: "Spec",
  document: "Doc",
  documents: "Docs",
  repository: "Repo",
  repositories: "Repos",
  experimental: "Exp",
  deprecated: "Depr",
  query: "Qry",
}
